import React, { useMemo } from 'react';
import type { SimulationResult } from '../scenario/types';
import RadarChart from './RadarChart';
import './ReportCard.css';

interface ReportCardProps {
  result: SimulationResult;
  id?: string;
}

export default function ReportCard({ result, id = 'foresight-report-card' }: ReportCardProps) {
  const circumference = 2 * Math.PI * 42;
  const scoreOffset = circumference - (result.overall_score / 100) * circumference;

  const scoreColor = useMemo(() => {
    if (result.overall_score >= 75) return '#10b981';
    if (result.overall_score >= 50) return '#06b6d4';
    if (result.overall_score >= 25) return '#f59e0b';
    return '#ef4444';
  }, [result.overall_score]);

  return (
    <div id={id} className="report-card">
      <div className="report-card__bg-glow"></div>
      
      <div className="report-card__header">
        <div className="report-card__brand">
          <div className="report-card__logo">🔮</div>
          <div className="report-card__name">Foresight AI</div>
        </div>
        <div className="report-card__meta">
          <span>{result.domain}</span>
          <span style={{ color: '#fd6925', fontWeight: 600 }}>SDG 9</span>
          <span style={{ color: '#f99d25', fontWeight: 600 }}>SDG 11</span>
          <span>•</span>
          <span>{new Date(result.timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}</span>
        </div>
      </div>

      <div className="report-card__body">
        <div className="report-card__left">
          <h2 className="report-card__query">"{result.query}"</h2>
          
          <div className="report-card__summary glass">
            {result.overall_summary}
          </div>
          
          <div className="report-card__score-box">
             <div className="dashboard__overall-score" style={{ transform: 'scale(1.2)', transformOrigin: 'left center' }}>
              <svg className="dashboard__overall-ring" viewBox="0 0 100 100">
                <circle className="dashboard__overall-ring-bg" cx="50" cy="50" r="42" />
                <circle 
                  className="dashboard__overall-ring-fill" 
                  cx="50" cy="50" r="42" 
                  stroke={scoreColor}
                  strokeDasharray={circumference}
                  strokeDashoffset={scoreOffset}
                />
              </svg>
              <span className="dashboard__overall-value" style={{ color: scoreColor }}>
                {Math.round(result.overall_score)}
              </span>
            </div>
            <div className="report-card__score-label">Overall Impact Score</div>
          </div>
        </div>

        <div className="report-card__right">
           <div className="report-card__radar-wrapper">
              <RadarChart impacts={result.impacts} size={360} />
           </div>
        </div>
      </div>
      
      <div className="report-card__footer">
        Generated by Foresight AI Decision Engine
      </div>
    </div>
  );
}
