import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      nav: {
        foresight: 'Foresight',
        aiDecisionEngine: 'AI Decision Engine',
        aiReady: 'AI Ready',
        simulate: 'Simulate',
        history: 'History'
      },
      home: {
        poweredBy: 'Powered by AI + Real Data',
        exploreFuture: 'Explore the <1>Future</1> Before It Happens',
        subtitle: 'Describe any "what if" scenario and our AI will simulate its impact across financial, environmental, human, risk, and opportunity dimensions.',
        simulateFuture: 'Simulate Future',
        simulating: 'Simulating...',
        examples: {
          ex1: 'What if Hyderabad banned petrol bikes by 2030?',
          ex2: 'What if all auto-rickshaws in Hyderabad became electric?',
          ex3: 'What if Hyderabad doubled its metro network by 2028?',
          ex4: 'What if EV charging stations tripled in Hyderabad next year?',
          ex5: 'What if Hyderabad imposed congestion pricing in the city center?'
        },
        placeholders: {
          p1: 'What if Hyderabad banned petrol bikes by 2030?',
          p2: 'What if every school switched to electric buses?',
          p3: 'What if the city doubled its metro coverage?',
          p4: 'Describe any scenario and explore its impact…'
        }
      },
      dashboard: {
        newScenario: '← New Scenario',
        scenarioAnalyzed: 'Scenario Analyzed',
        overallImpact: 'Overall Impact',
        multiDimensional: 'Multi-Dimensional Impact Analysis',
        detailedBreakdown: '📊 Detailed Impact Breakdown'
      },
      history: {
        title: '📋 Scenario History',
        noScenariosYet: 'No scenarios yet',
        runFirstSimulation: 'Run your first simulation to see it here!',
        scenariosCount: 'scenarios',
        clickExpand: '▼ {{count}} metrics — click to expand',
        clickCollapse: '▲ Click to collapse'
      },
      loading: {
        title: 'Simulating Future Outcomes',
        subtitle: 'Our AI is analyzing your scenario across financial, environmental, human, risk, and opportunity dimensions.',
        steps: {
          s1: 'Interpreting your scenario…',
          s2: 'Querying knowledge graph…',
          s3: 'Running calculations…',
          s4: 'Generating AI analysis…',
          s5: 'Compiling results…'
        }
      },
      categories: {
        financial: 'Financial',
        environmental: 'Environmental',
        human: 'Human',
        risks: 'Risks',
        opportunities: 'Opportunities'
      },
      common: {
        confidence: 'confidence',
        kg: 'Knowledge Graph',
        aiEstimate: 'AI Estimate',
        kgDesc: 'Calculated from verifiable public datasets and government records',
        aiDesc: 'Directional estimate generated by Google Gemini based on economic models'
      },
      auth: {
        signIn: 'Sign In',
        signOut: 'Sign Out',
        login: 'Login',
        register: 'Register',
        email: 'Email',
        password: 'Password',
        name: 'Name',
        welcomeBack: '✨ Welcome back, {{name}}',
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: 'Already have an account?',
        creatingAccount: 'Creating account...',
        signingIn: 'Signing in...',
        registerSuccess: 'Successfully registered',
        logoutSuccess: 'Successfully signed out'
      }
    }
  },
  hi: {
    translation: {
      nav: {
        foresight: 'फोरसाइट',
        aiDecisionEngine: 'एआई निर्णय इंजन',
        aiReady: 'एआई तैयार है',
        simulate: 'अनुकरण करें',
        compare: 'तुलना करें',
        history: 'इतिहास'
      },
      auth: {
        signIn: 'साइन इन करें',
        signOut: 'साइन आउट करें',
        login: 'लॉग इन करें',
        register: 'रजिस्टर करें',
        email: 'ईमेल',
        password: 'पासवर्ड',
        name: 'नाम',
        welcomeBack: '✨ वापसी पर स्वागत है, {{name}}',
        dontHaveAccount: "खाता नहीं है?",
        alreadyHaveAccount: 'पहले से ही खाता है?',
        creatingAccount: 'खाता बनाया जा रहा है...',
        signingIn: 'साइन इन हो रहा है...',
        registerSuccess: 'सफलतापूर्वक पंजीकृत',
        logoutSuccess: 'सफलतापूर्वक साइन आउट किया गया'
      },
      home: {
        poweredBy: 'एआई + वास्तविक डेटा द्वारा संचालित',
        exploreFuture: 'घटित होने से पहले <1>भविष्य</1> का अन्वेषण करें',
        subtitle: 'किसी भी "क्या हो अगर" परिदृश्य का वर्णन करें और हमारा एआई वित्तीय, पर्यावरणीय, मानवीय, जोखिम और अवसर आयामों में इसके प्रभाव का अनुकरण करेगा।',
        simulateFuture: 'भविष्य का अनुकरण करें',
        simulating: 'अनुकरण हो रहा है...',
        examples: {
          ex1: 'क्या हो अगर हैदराबाद 2030 तक पेट्रोल बाइक पर प्रतिबंध लगा दे?',
          ex2: 'क्या हो अगर हैदराबाद में सभी ऑटो-रिक्शा इलेक्ट्रिक हो जाएं?',
          ex3: 'क्या हो अगर हैदराबाद 2028 तक अपने मेट्रो नेटवर्क को दोगुना कर दे?',
          ex4: 'क्या हो अगर अगले साल हैदराबाद में ईवी चार्जिंग स्टेशन तीन गुना हो जाएं?',
          ex5: 'क्या हो अगर हैदराबाद सिटी सेंटर में कंजेशन प्राइसिंग लागू करे?'
        },
        placeholders: {
          p1: 'क्या हो अगर हैदराबाद 2030 तक पेट्रोल बाइक पर प्रतिबंध लगा दे?',
          p2: 'क्या हो अगर हर स्कूल इलेक्ट्रिक बसों में बदल जाए?',
          p3: 'क्या हो अगर शहर अपनी मेट्रो कवरेज को दोगुना कर दे?',
          p4: 'किसी भी परिदृश्य का वर्णन करें और उसके प्रभाव का अन्वेषण करें…'
        }
      },
      dashboard: {
        newScenario: '← नया परिदृश्य',
        scenarioAnalyzed: 'परिदृश्य विश्लेषित',
        overallImpact: 'कुल प्रभाव',
        multiDimensional: 'बहु-आयामी प्रभाव विश्लेषण',
        detailedBreakdown: '📊 विस्तृत प्रभाव विवरण'
      },
      history: {
        title: '📋 परिदृश्य इतिहास',
        noScenariosYet: 'अभी कोई परिदृश्य नहीं',
        runFirstSimulation: 'अपना पहला अनुकरण चलाने के लिए यहां देखें!',
        scenariosCount: 'परिदृश्य',
        clickExpand: '▼ {{count}} मेट्रिक्स — विस्तार करने के लिए क्लिक करें',
        clickCollapse: '▲ संक्षिप्त करने के लिए क्लिक करें'
      },
      loading: {
        title: 'भविष्य के परिणामों का अनुकरण',
        subtitle: 'हमारा AI वित्तीय, पर्यावरणीय, मानवीय, जोखिम और अवसर आयामों में आपके परिदृश्य का विश्लेषण कर रहा है।',
        steps: {
          s1: 'आपके परिदृश्य की व्याख्या की जा रही है…',
          s2: 'नॉलेज ग्राफ खोजा जा रहा है…',
          s3: 'गणनाएं चल रही हैं…',
          s4: 'AI विश्लेषण उत्पन्न किया जा रहा है…',
          s5: 'परिणाम संकलित किए जा रहे हैं…'
        }
      },
      categories: {
        financial: 'वित्तीय',
        environmental: 'पर्यावरणीय',
        human: 'मानवीय',
        risks: 'जोखिम',
        opportunities: 'अवसर'
      },
      common: {
        confidence: 'विश्वास',
        kg: 'नॉलेज ग्राफ',
        aiEstimate: 'एआई अनुमान',
        kgDesc: 'सत्यापन योग्य सार्वजनिक डेटासेट और सरकारी रिकॉर्ड से गणना की गई',
        aiDesc: 'आर्थिक मॉडल के आधार पर Google Gemini द्वारा उत्पन्न अनुमान'
      }
    }
  },
  te: {
    translation: {
      nav: {
        foresight: 'ఫోర్‌సైట్',
        aiDecisionEngine: 'AI నిర్ణయ యంత్రం',
        aiReady: 'AI సిద్ధంగా ఉంది',
        simulate: 'సిమ్యులేట్ చేయండి',
        history: 'చరిత్ర'
      },
      home: {
        poweredBy: 'AI + రియల్ డేటాతో పవర్ చేయబడింది',
        exploreFuture: 'జరగక ముందే <1>భవిష్యత్తును</1> అన్వేషించండి',
        subtitle: 'ఏదైనా "ఏమి జరిగితే" అనే పరిస్థితిని వివరించండి, మరియు మా AI ఆర్థిక, పర్యావరణ, మానవ, ప్రమాద, మరియు అవకాశాల కోణాల్లో దాని ప్రభావాన్ని సిమ్యులేట్ చేస్తుంది.',
        simulateFuture: 'భవిష్యత్తును సిమ్యులేట్ చేయండి',
        simulating: 'సిమ్యులేట్ చేస్తోంది...',
        examples: {
          ex1: 'హైదరాబాద్ 2030 నాటికి పెట్రోల్ బైక్‌లను నిషేధిస్తే ఏమి జరుగుతుంది?',
          ex2: 'హైదరాబాద్‌లోని అన్ని ఆటో-రిక్షాలు ఎలక్ట్రిక్‌గా మారితే ఏమి జరుగుతుంది?',
          ex3: 'హైదరాబాద్ 2028 నాటికి తన మెట్రో నెట్‌వర్క్‌ను రెట్టింపు చేస్తే ఏమి జరుగుతుంది?',
          ex4: 'వచ్చే ఏడాది హైదరాబాద్‌లో EV ఛార్జింగ్ స్టేషన్లు మూడు రెట్లు పెరిగితే ఏమి జరుగుతుంది?',
          ex5: 'హైదరాబాద్ సిటీ సెంటర్‌లో రద్దీ ధరలను విధిస్తే ఏమి జరుగుతుంది?'
        },
        placeholders: {
          p1: 'హైదరాబాద్ 2030 నాటికి పెట్రోల్ బైక్‌లను నిషేధిస్తే ఏమి జరుగుతుంది?',
          p2: 'ప్రతి పాఠశాల ఎలక్ట్రిక్ బస్సులకు మారితే ఏమి జరుగుతుంది?',
          p3: 'నగరం తన మెట్రో కవరేజీని రెట్టింపు చేస్తే ఏమి జరుగుతుంది?',
          p4: 'ఏదైనా పరిస్థితిని వివరించండి మరియు దాని ప్రభావాన్ని అన్వేషించండి…'
        }
      },
      dashboard: {
        newScenario: '← కొత్త పరిస్థితి',
        scenarioAnalyzed: 'పరిస్థితి విశ్లేషించబడింది',
        overallImpact: 'మొత్తం ప్రభావం',
        multiDimensional: 'బహుళ-పరిమాణ ప్రభావ విశ్లేషణ',
        detailedBreakdown: '📊 వివరణాత్మక ప్రభావం బ్రేక్‌డౌన్'
      },
      history: {
        title: '📋 పరిస్థితి చరిత్ర',
        noScenariosYet: 'ఇంకా పరిస్థితులు లేవు',
        runFirstSimulation: 'దీనిని చూడటానికి మీ మొదటి అనుకరణను ప్రారంభించండి!',
        scenariosCount: 'పరిస్థితులు',
        clickExpand: '▼ {{count}} కొలమానాలు — విస్తరించడానికి క్లిక్ చేయండి',
        clickCollapse: '▲ కుదించడానికి క్లిక్ చేయండి'
      },
      loading: {
        title: 'భవిష్యత్తు ఫలితాలను అనుకరిస్తోంది',
        subtitle: 'మా AI ఆర్థిక, పర్యావరణ, మానవ, ప్రమాద, మరియు అవకాశాల కోణాల్లో మీ పరిస్థితిని విశ్లేషిస్తోంది.',
        steps: {
          s1: 'మీ పరిస్థితిని వివరిస్తోంది…',
          s2: 'నాలెడ్జ్ గ్రాఫ్‌ను శోధిస్తోంది…',
          s3: 'లెక్కలు వేస్తోంది…',
          s4: 'AI విశ్లేషణను ఉత్పత్తి చేస్తోంది…',
          s5: 'ఫలితాలను సంకలనం చేస్తోంది…'
        }
      },
      categories: {
        financial: 'ఆర్థిక',
        environmental: 'పర్యావరణ',
        human: 'మానవ',
        risks: 'ప్రమాదాలు',
        opportunities: 'అవకాశాలు'
      },
      common: {
        confidence: 'విశ్వాసం',
        kg: 'నాలెడ్జ్ గ్రాఫ్',
        aiEstimate: 'AI అంచనా',
        kgDesc: 'ధృవీకరించదగిన పబ్లిక్ డేటాసెట్‌లు మరియు ప్రభుత్వ రికార్డుల నుండి లెక్కించబడింది',
        aiDesc: 'ఆర్థిక నమూనాల ఆధారంగా Google Gemini ద్వారా రూపొందించబడిన అంచనా'
      }
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'en', // default language
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
