/**
 * Foresight PDF Export Utility
 * Generates a premium multi-page simulation report using jsPDF.
 *
 * NOTE: jsPDF built-in fonts only support Latin-1. All emojis and special
 * Unicode chars (Rs., etc.) must be replaced with ASCII-safe equivalents.
 */

import jsPDF from 'jspdf';
import type { SimulationResult } from '../features/scenario/types';

// ── Palette ────────────────────────────────────────────────────
const DARK   = [10,  10,  26]  as const;
const PURPLE = [109, 40,  217] as const;
const CYAN   = [6,   182, 212] as const;
const WHITE  = [255, 255, 255] as const;
const LGRAY  = [200, 200, 220] as const;
const MGRAY  = [130, 130, 155] as const;

const CAT_COLORS: Record<string, readonly [number, number, number]> = {
  financial:    [245, 158,  11],
  environmental:[ 16, 185, 129],
  human:        [  6, 182, 212],
  risks:        [239,  68,  68],
  opportunities:[124,  58, 237],
};

// ASCII-safe category labels (no emoji)
const CAT_LABEL: Record<string, string> = {
  financial:    'FINANCIAL',
  environmental:'ENVIRONMENTAL',
  human:        'HUMAN',
  risks:        'RISKS',
  opportunities:'OPPORTUNITIES',
};

const CAT_ICON: Record<string, string> = {
  financial:    '[Fin]',
  environmental:'[Env]',
  human:        '[Hum]',
  risks:        '[Risk]',
  opportunities:'[Opp]',
};

// Replace special Unicode chars with ASCII-safe equivalents for Latin-1 jsPDF fonts
function sanitize(text: string): string {
  return text
    .replace(/\u20b9|\u20a8/g, 'Rs.')  // rupee signs
    .replace(/\u2014|\u2015/g, ' - ')  // em dash
    .replace(/\u2013/g, '-')            // en dash
    .replace(/\u2026/g, '...')          // ellipsis
    .replace(/\u00d7/g, 'x')            // multiplication sign
    .replace(/\u2019|\u2018/g, "'")     // curly apostrophes
    .replace(/\u201c|\u201d/g, '"')    // curly quotes
    .replace(/[^\x00-\xFF]/g, '')       // strip remaining non-Latin-1
    .replace(/  +/g, ' ')               // collapse multiple spaces
    .trim();
}

function scoreColor(score: number): readonly [number, number, number] {
  if (score >= 75) return [16, 185, 129];
  if (score >= 50) return [6, 182, 212];
  if (score >= 25) return [245, 158, 11];
  return [239, 68, 68];
}

function setFill(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setFillColor(c[0], c[1], c[2]);
}
function setDraw(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setDrawColor(c[0], c[1], c[2]);
}
function setColor(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setTextColor(c[0], c[1], c[2]);
}

function roundRect(
  doc: jsPDF,
  x: number, y: number, w: number, h: number, r: number,
  fill: readonly [number, number, number],
) {
  setFill(doc, fill);
  doc.roundedRect(x, y, w, h, r, r, 'F');
}

function scoreBar(
  doc: jsPDF,
  x: number, y: number, w: number, h: number,
  score: number,
  color: readonly [number, number, number],
) {
  setFill(doc, [35, 35, 58]);
  doc.roundedRect(x, y, w, h, h / 2, h / 2, 'F');
  const filled = Math.max((score / 100) * w, h);
  setFill(doc, color);
  doc.roundedRect(x, y, filled, h, h / 2, h / 2, 'F');
}

function addHeader(doc: jsPDF, pw: number) {
  setFill(doc, DARK);
  doc.rect(0, 0, pw, 22, 'F');
  setFill(doc, PURPLE);
  doc.rect(0, 22, pw, 2, 'F');

  setColor(doc, CYAN);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('FORESIGHT', 14, 14);

  setColor(doc, LGRAY);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text('AI "What If" Decision Engine', 14, 19);

  setColor(doc, MGRAY);
  doc.setFontSize(7);
  doc.text('Powered by Gemini + Knowledge Graph', pw - 14, 14, { align: 'right' });
  doc.text('foresight.ai', pw - 14, 19, { align: 'right' });
}

function addFooter(doc: jsPDF, pw: number, ph: number, page: number) {
  setFill(doc, [18, 18, 36]);
  doc.rect(0, ph - 10, pw, 10, 'F');
  setColor(doc, MGRAY);
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
  doc.text(`Generated by Foresight AI  |  ${dateStr}`, 14, ph - 3.5);
  doc.text(`Page ${page}`, pw - 14, ph - 3.5, { align: 'right' });
}

function newPage(doc: jsPDF, pw: number, ph: number, pageRef: { n: number }) {
  pageRef.n++;
  doc.addPage();
  setFill(doc, DARK);
  doc.rect(0, 0, pw, ph, 'F');
  addHeader(doc, pw);
  return 34; // starting y
}

export async function exportToPDF(result: SimulationResult): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const M  = 14;           // margin
  const CW = pw - M * 2;  // content width
  const pageRef = { n: 1 };

  // ── PAGE 1 ──────────────────────────────────────────────────
  setFill(doc, DARK);
  doc.rect(0, 0, pw, ph, 'F');
  addHeader(doc, pw);

  let y = 38;

  // Report label
  setColor(doc, CYAN);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('SCENARIO ANALYSIS REPORT', M, y);
  y += 6;

  // Query
  setColor(doc, WHITE);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  const qLines = doc.splitTextToSize(`"${sanitize(result.query)}"`, CW) as string[];
  qLines.forEach(line => { doc.text(line, M, y); y += 7.5; });
  y += 3;

  // Meta badges — all text is ASCII-safe
  const domainLabel = result.domain === 'hyderabad_ev_traffic'
    ? 'Hyderabad EV/Traffic'
    : result.domain;
  const dateLabel = new Date(result.timestamp).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'short', year: 'numeric',
  });
  const metaItems = [
    `[Domain] ${domainLabel}`,
    `[Date] ${dateLabel}`,
    result.processing_time_ms
      ? `[Time] ${(result.processing_time_ms / 1000).toFixed(1)}s`
      : null,
  ].filter(Boolean) as string[];

  let bx = M;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  metaItems.forEach(item => {
    const tw = doc.getTextWidth(item) + 8;
    roundRect(doc, bx, y, tw, 7, 2, [30, 30, 55]);
    setColor(doc, LGRAY);
    doc.text(item, bx + 4, y + 5);
    bx += tw + 3;
  });
  y += 13;

  // Overall score card
  const sc = Math.round(result.overall_score);
  const scCol = scoreColor(result.overall_score);
  roundRect(doc, M, y, CW, 36, 4, [18, 18, 40]);

  // Score number on left
  setColor(doc, scCol);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text(String(sc), M + 17, y + 23, { align: 'center' });

  // Label
  setColor(doc, MGRAY);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('OVERALL', M + 17, y + 8, { align: 'center' });
  doc.text('IMPACT', M + 17, y + 12.5, { align: 'center' });
  doc.text('SCORE', M + 17, y + 17, { align: 'center' });

  // Score bar
  const barX = M + 36;
  const barW = CW - 44;
  scoreBar(doc, barX, y + 13, barW, 5, result.overall_score, scCol);
  setColor(doc, LGRAY);
  doc.setFontSize(7);
  doc.text(`${sc}/100`, barX + barW + 4, y + 17);

  // Mini axis pills below bar
  const colW = barW / result.impacts.length;
  result.impacts.forEach((impact, i) => {
    const col = CAT_COLORS[impact.category] ?? CYAN;
    const ax = barX + i * colW;
    setColor(doc, col);
    doc.setFontSize(5.5);
    doc.setFont('helvetica', 'bold');
    doc.text(impact.category.substring(0, 3).toUpperCase(), ax + colW / 2, y + 26, { align: 'center' });
    doc.setFontSize(9);
    doc.text(String(Math.round(impact.score)), ax + colW / 2, y + 32, { align: 'center' });
  });
  y += 43;

  // Executive summary
  setColor(doc, CYAN);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('EXECUTIVE SUMMARY', M, y);
  y += 2;
  setFill(doc, PURPLE);
  doc.rect(M, y + 1, CW, 0.5, 'F');
  y += 5;

  setColor(doc, LGRAY);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  const sumLines = doc.splitTextToSize(sanitize(result.overall_summary), CW) as string[];
  sumLines.forEach(line => { doc.text(line, M, y); y += 5.5; });
  y += 5;

  // Impact axis overview
  setColor(doc, CYAN);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('IMPACT AXIS OVERVIEW', M, y);
  y += 5;

  for (const impact of result.impacts) {
    if (y + 18 > ph - 14) {
      addFooter(doc, pw, ph, pageRef.n);
      y = newPage(doc, pw, ph, pageRef);
    }
    const col = CAT_COLORS[impact.category] ?? CYAN;

    roundRect(doc, M, y, CW, 15, 2, [18, 18, 40]);

    // Category label
    setColor(doc, col);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `${CAT_ICON[impact.category] ?? ''} ${CAT_LABEL[impact.category] ?? impact.category.toUpperCase()}`,
      M + 3, y + 6,
    );

    // Score badge
    roundRect(doc, M + 3, y + 8, 22, 5, 1.5, col);
    setColor(doc, WHITE);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(`${Math.round(impact.score)}/100`, M + 14, y + 12, { align: 'center' });

    // Progress bar
    scoreBar(doc, M + 28, y + 10, CW - 48, 3, impact.score, col);

    // Source tag
    const srcLabel = impact.data_source === 'knowledge_graph' ? 'KG-Data' : 'AI Est.';
    setColor(doc, MGRAY);
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.text(srcLabel, pw - M - 3, y + 6, { align: 'right' });

    // Summary text
    setColor(doc, [170, 170, 200]);
    doc.setFontSize(7);
    const summaryShort = sanitize(impact.summary);
    const s = summaryShort.length > 85 ? summaryShort.substring(0, 82) + '...' : summaryShort;
    doc.text(s, M + 3, y + 13.5);

    y += 18;
  }

  addFooter(doc, pw, ph, pageRef.n);

  // ── PAGE 2: Detailed Metrics ──────────────────────────────────
  y = newPage(doc, pw, ph, pageRef);

  setColor(doc, CYAN);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('DETAILED METRIC BREAKDOWN', M, y);
  y += 9;

  for (const impact of result.impacts) {
    if (impact.details.length === 0) continue;
    const col = CAT_COLORS[impact.category] ?? CYAN;

    if (y + 18 > ph - 14) {
      addFooter(doc, pw, ph, pageRef.n);
      y = newPage(doc, pw, ph, pageRef);
    }

    // Section header
    setFill(doc, col);
    doc.rect(M, y, 3, 9, 'F');
    setColor(doc, col);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `${CAT_ICON[impact.category]} ${CAT_LABEL[impact.category] ?? impact.category.toUpperCase()}`,
      M + 6, y + 6.5,
    );
    setColor(doc, MGRAY);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    const src = impact.data_source === 'knowledge_graph' ? 'Knowledge Graph' : 'AI Estimate';
    doc.text(
      `Score: ${Math.round(impact.score)}/100  |  Source: ${src}`,
      pw - M, y + 6.5, { align: 'right' },
    );
    y += 13;

    for (const detail of impact.details) {
      if (y + 26 > ph - 14) {
        addFooter(doc, pw, ph, pageRef.n);
        y = newPage(doc, pw, ph, pageRef);
      }

      roundRect(doc, M, y, CW, 22, 2, [20, 20, 44]);

      // Metric name — left, bold
      setColor(doc, WHITE);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      const metricText = sanitize(detail.metric);
      doc.text(metricText, M + 4, y + 7);

      // Value — check if it fits on the same line, otherwise drop to line 2
      setColor(doc, col);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      const valText = sanitize(detail.value);
      const metricWidth = doc.getTextWidth(metricText);
      const valWidth = doc.getTextWidth(valText);
      const sameLineGap = 8; // min gap between metric and value
      const valFitsOneLine = metricWidth + valWidth + sameLineGap < CW - 8;

      if (valFitsOneLine) {
        doc.text(valText, pw - M - 4, y + 7, { align: 'right' });
      } else {
        // Drop value to a second line, left-aligned under the metric
        setColor(doc, col);
        doc.setFontSize(7.5);
        doc.text(valText, M + 4, y + 12);
      }

      // Explanation
      const expY = valFitsOneLine ? y + 12 : y + 17;
      setColor(doc, [160, 160, 190]);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      const expLines = doc.splitTextToSize(sanitize(detail.explanation), CW - 10) as string[];
      expLines.slice(0, 2).forEach((line, li) => {
        doc.text(line, M + 4, expY + li * 4);
      });

      // Chips row
      const chipY = expY + (expLines.length > 1 ? 8 : 4) + 2;

      // Confidence chip
      const confBg: readonly [number, number, number] =
        detail.confidence === 'high'   ? [16, 120, 80] :
        detail.confidence === 'medium' ? [140, 90,   0] :
                                          [160,  40,  40];
      roundRect(doc, M + 4, chipY, 30, 4.5, 1.5, confBg);
      setColor(doc, WHITE);
      doc.setFontSize(6);
      doc.setFont('helvetica', 'bold');
      doc.text(`${detail.confidence.toUpperCase()} CONF.`, M + 19, chipY + 3.2, { align: 'center' });

      // Source chip
      const srcBg: readonly [number, number, number] =
        detail.source === 'knowledge_graph' ? [6, 78, 59] : [67, 20, 120];
      roundRect(doc, M + 36, chipY, 28, 4.5, 1.5, srcBg);
      setColor(doc, WHITE);
      doc.setFontSize(6);
      doc.text(
        detail.source === 'knowledge_graph' ? 'KG BACKED' : 'AI ESTIMATE',
        M + 50, chipY + 3.2, { align: 'center' },
      );

      y += 26;
    }
    y += 3;
  }

  addFooter(doc, pw, ph, pageRef.n);

  // Save
  const slug = sanitize(result.query).substring(0, 30).replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`Foresight_Report_${slug}_${Date.now()}.pdf`);
}
